
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajwtcfatyfodparcmuyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqd3RjZmF0eWZvZHBhcmNtdXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDk2NjYsImV4cCI6MjA2MTkyNTY2Nn0.9ArCb8aGHKdBYuTvxoT-Nsx5XT3R_TlG40lYW_2We9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get user role
export const getUserRole = async () => {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;
  
  const { data } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  
  return data?.role;
};

// Helper function to create notification
export const createNotification = async (userId, type, message, relatedBid = null) => {
  try {
    const { error } = await supabase.from('notifications').insert({
      user_id: userId,
      type,
      message,
      related_bid: relatedBid,
      seen: false
    });
    
    if (error) console.error('Failed to create notification:', error);
    return !error;
  } catch (err) {
    console.error('Failed to create notification:', err);
    return false;
  }
};
